import mcdonalds from "./assets/mcdonalds.svg";
import tesla from "./assets/tesla.svg";
import gm from "./assets/gm.svg";
import aarp from "./assets/aarp.svg";
import disney from "./assets/disney.svg";
import prime from "./assets/prime.svg";
import match from "./assets/match.svg";
import chevy from "./assets/chevy.svg";
import gm2 from "./assets/gm2.svg";

const data = [
  {
    key: "1",
    logo: mcdonalds,
    name: "McDonalds",
    sub_name: "Big Mac Jumbo",
    status: "Confirmed",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "25/05/2023",
    action: "",
    active_orders: "10",
  },
  {
    key: "2",
    logo: tesla,
    name: "Tesla",
    sub_name: "Model X",
    status: "Delivered",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "26/05/2023",
    action: "",
    active_orders: "4",
  },
  {
    key: "3",
    logo: gm,
    name: "GM",
    sub_name: "Alternator Car Parts",
    status: "Refund Completed",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "26/05/2023",
    action: "",
    active_orders: "30",
  },
  {
    key: "4",
    logo: aarp,
    name: "AARP",
    sub_name: "Health Care Package Adult A1",
    status: "Pending",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "25/05/2023",
    action: "",
    active_orders: "27",
  },
  {
    key: "5",
    logo: disney,
    name: "Disney",
    sub_name: "Renewal Subscription",
    status: "Pending",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "3/05/2023",
    action: "",
    active_orders: "10",
  },
  {
    key: "6",
    logo: prime,
    name: "Prime Theraputics",
    sub_name: "Natural Oil",
    status: "Refund Completed",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "28/05/2023",
    action: "",
    active_orders: "6",
  },
  {
    key: "7",
    logo: match,
    name: "Match.com",
    sub_name: "Renewal Subscription",
    status: "Delivered",
    item: "",
    quantity: "1000",
    price: "",
    placed_on: "10/05/2023",
    action: "",
    active_orders: "5",
  },
  {
    key: "8",
    logo: chevy,
    name: "Chevy",
    sub_name: "FX234A",
    status: "Confirmed",
    item: "",
    quantity: "666",
    price: "",
    placed_on: "15/05/2023",
    action: "",
    active_orders: "10",
  },
  {
    key: "9",
    logo: gm2,
    name: "GM",
    sub_name: "Car Parts AJZ89B",
    status: "Confirmed",
    item: "",
    quantity: "233",
    price: "",
    placed_on: "10/05/2023",
    action: "",
    active_orders: "8",
  },
];

export default data;
